# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: admin@symblog.dev
    blogger_blog.emails.thank_you_message: Your contact enquiry was successfully sent. Thank you!
    blogger_blog.comments.latest_comment_limit: 10